[tool.poetry]
name = "cookiecutter-machine-learning"
version = "1.0.3"
description = "A cookiecutter template for machine learning projects in Python."
license = "MIT"
authors = ["Eric Young <ESKYoung@users.noreply.github.com>"]
maintainers = ["Eric Young <ESKYoung@users.noreply.github.com>"]
readme = "README.md"
homepage = "https://ESKYoung.github.io/cookiecutter-machine-learning"
repository = "https://github.com/ESKYoung/cookiecutter-machine-learning"
documentation = "https://ESKYoung.github.io/cookiecutter-machine-learning"
keywords = []
classifiers = []
packages = [
    {include = "cookiecutter_machine_learning", from = "src"},
    {include = "hooks"},
]
include = []
exclude = []

[tool.poetry.dependencies]
python = "^3.9"
cruft = "^2.12.0"
cookiecutter = "^2.1.1"

[tool.poetry.group.ci-cd]
optional = true

[tool.poetry.group.ci-cd.dependencies]
nox = "^2022.11.21"
nox-poetry = "^1.0.2"

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
myst-parser = {extras = ["linkify"], version = "^0.18.1"}
pydata-sphinx-theme = "^0.12.0"
Sphinx = "^5.1.1"
sphinx-copybutton = "^0.5.1"

[tool.poetry.group.pre-commit]
optional = true

[tool.poetry.group.pre-commit.dependencies]
black = "^22.12.0"
detect-secrets = "^1.4.0"
flake8 = "^6.0.0"
flake8-bandit = "^4.1.1"
flake8-bugbear = "^23.1.20"
flake8-docstrings = "^1.6.0"
flake8-rst-docstrings = "^0.3.0"
isort = "^5.11.4"
mypy = "^0.991"
pre-commit = "^2.21.0"
pre-commit-hooks = "^4.4.0"
safety = "^2.3.5"

[tool.poetry.group.testing]
optional = true

[tool.poetry.group.testing.dependencies]
coverage = {extras = ["toml"], version = "^7.0.5"}
pytest = "^7.2.1"
pytest-cookies = "^0.6.1"
pytest-cov = "^4.0.0"
pytest-mock = "^3.10.0"
pytest-xdist = "^3.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
config = "./pyproject.toml"
force-exclude = "^/\\{\\{ cookiecutter\\.repository_name \\}\\}/pyproject\\.toml$"

[tool.coverage.paths]
source = ["hooks", "src"]

[tool.coverage.report]
exclude_lines = ["if __name__ == .__main__.:"]
fail_under = 90
show_missing = true

[tool.isort]
profile = "black"

[tool.mypy]
strict = true
pretty = true
show_column_numbers = true
show_error_codes = true
show_error_context = true

[tool.nbqa.addopts]
black = [
    "--config=./pyproject.toml",
    '--force-exclude="^/\\{\\{ cookiecutter\\.repository_name \\}\\}/pyproject\\.toml$"'
]

[tool.nbqa.exclude]
black = "^/\\{\\{ cookiecutter\\.repository_name \\}\\}/pyproject\\.toml$"
flake8 = "^/\\{\\{ cookiecutter\\.repository_name \\}\\}/pyproject\\.toml$"
isort = "^/\\{\\{ cookiecutter\\.repository_name \\}\\}/pyproject\\.toml$"
mypy = "^/\\{\\{ cookiecutter\\.repository_name \\}\\}/pyproject\\.toml$"

[tool.pytest.ini_options]
addopts = ["-vv", "--doctest-modules", "--keep-baked-projects"]
doctest_optionflags = "NORMALIZE_WHITESPACE"
testpaths = ["./tests"]
