[tool.poetry]
name = "{{ cookiecutter.repository_name }}"
version = "{{ cookiecutter.release }}"
description = "{{ cookiecutter.description }}"
{% if cookiecutter.license == "MIT" -%}
license = "MIT"
{% endif -%}
authors = ["{{ cookiecutter.author }} <{{ cookiecutter.email }}>"]
maintainers = ["{{ cookiecutter.author }} <{{ cookiecutter.email }}>"]
readme = "README.md"
homepage = "https://{{ cookiecutter.github_username }}.github.io/{{ cookiecutter.repository_name }}"
repository = "https://github.com/{{ cookiecutter.github_username }}/{{ cookiecutter.repository_name }}"
documentation = "https://{{ cookiecutter.github_username }}.github.io/{{ cookiecutter.repository_name }}"
keywords = []
classifiers = []
packages = [
    {include = "{{ cookiecutter.package_name }}", from = "src"},
]
include = []
exclude = []

[tool.poetry.dependencies]
python = "^3.9"
cruft = "^2.11.0"
cookiecutter = "^2.1.1"

[tool.poetry.group.ci-cd]
optional = true

[tool.poetry.group.ci-cd.dependencies]
nox = "^2022.8.7"
nox-poetry = "^1.0.1"

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
myst-parser = {extras = ["linkify"], version = "^0.18.0"}
pydata-sphinx-theme = "^0.9.0"
Sphinx = "^5.1.1"
sphinx-copybutton = "^0.5.0"

[tool.poetry.group.pre-commit]
optional = true

[tool.poetry.group.pre-commit.dependencies]
black = "^22.6.0"
detect-secrets = "^1.3.0"
flake8 = "^5.0.4"
flake8-bandit = "v4.1.1"
flake8-bugbear = "^22.7.1"
flake8-docstrings = "^1.6.0"
flake8-rst-docstrings = "^0.2.7"
isort = "^5.10.1"
mypy = "^0.971"
nbqa = "^1.4.0"
nbstripout = "^0.6.0"
pre-commit = "^2.20.0"
pre-commit-hooks = "^4.3.0"
safety = "^2.1.1"

[tool.poetry.group.testing]
optional = true

[tool.poetry.group.testing.dependencies]
coverage = {extras = ["toml"], version = "^6.4.4"}
pytest = "^7.1.2"
pytest-cov = "^3.0.0"
pytest-mock = "^3.8.2"
pytest-xdist = "^2.5.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.coverage.paths]
source = ["src"]

[tool.coverage.report]
exclude_lines = ["if __name__ == .__main__.:"]
fail_under = 90
show_missing = true

[tool.isort]
profile = "black"

[tool.mypy]
strict = true
pretty = true
show_column_numbers = true
show_error_codes = true
show_error_context = true

[tool.pytest.ini_options]
addopts = ["-vv", "--doctest-modules"]
doctest_optionflags = "NORMALIZE_WHITESPACE"
testpaths = ["./tests"]
