name: Update repository with Cruft

permissions:
  contents: write
  pull-requests: write

on:
  schedule:
    - cron: "0 2 * * 1"

env:
  PYTHON_VERSION: "3.10"

jobs:
  cruft-autoupdate:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout the revision
        uses: actions/checkout@v4

      - name: Check if `.cruft.json` exists
        id: check-cruft-link
        run: |
          if [ -f .cruft.json ]; then
            if [ "$(jq -r '.template | startswith("git@github.com")' .cruft.json)" = 'true' ]; then
              printf "GitHub Action unsupported for private \`cruft\` templates or links via SSH. Disable this workflow until the template link has been switched to public HTTPS!\n"
              exit 1
            else
              echo "CURRENT_TEMPLATE_RELEASE=$(jq -r '.checkout' .cruft.json)" >> "$GITHUB_OUTPUT"
            fi
          else
            printf "No \'.cruft.json\' file found!'\n"
            exit 1
          fi

      - name: Install Poetry
        id: install-poetry
        uses: ./.github/actions/install-poetry
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Cache Poetry virtual environment
        id: cache-poetry-venv
        uses: actions/cache@v4
        with:
          path: .venv
          key: cache-${{ github.repository }}-${{ github.job }}-poetry-venv-${{ runner.os }}-${{ steps.install-poetry.outputs.full-python-version }}-${{ hashFiles('poetry.lock') }}
          restore-keys: cache-${{ github.repository }}-${{ github.job }}-poetry-venv-${{ runner.os }}-${{ steps.install-poetry.outputs.full-python-version }}-

      - name: Install dependencies
        if: ${{ steps.cache-poetry-venv.outputs.cache-hit != 'true' }}
        run: poetry install --only=cookiecutter --sync --no-ansi

      - name: Get latest release tag from template
        id: get-latest-release
        run: |
          curl -sS "https://api.github.com/repos/ESKYoung/cookiecutter-machine-learning/tags" | \
          jq -r '.[0].name' | \
          awk '{print "LATEST_TEMPLATE_RELEASE="$1}' >> "$GITHUB_OUTPUT"

      - name: Check if updates are available
        id: check-cruft-updates
        continue-on-error: false
        run: |
          if ! poetry run cruft check --checkout="${{ steps.get-latest-release.outputs.LATEST_TEMPLATE_RELEASE }}"; then
            echo "CRUFT_CHANGED=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Run `cruft update` if changes have been detected
        if: ${{ steps.check-cruft-updates.outputs.CRUFT_CHANGED == 'true' }}
        run: |
          poetry run cruft update --checkout="${{ steps.get-latest-release.outputs.LATEST_TEMPLATE_RELEASE }}" --skip-apply-ask --refresh-private-variables
          git restore --staged .

      - name: Create GitHub Pull Request
        if: ${{ !env.ACT && steps.check-cruft-updates.outputs.CRUFT_CHANGED == 'true' }}
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          add-paths: .
          commit-message: |
            chore: incorporate new `cruft` updates

            This commit updates the repository to the latest release `${{ steps.get-latest-release.outputs.LATEST_TEMPLATE_RELEASE}}` from `${{ steps.check-cruft-link.outputs.CURRENT_TEMPLATE_RELEASE}}`.

            For more information on the latest release, see its changelog:
            https://github.com/ESKYoung/cookiecutter-machine-learning/releases/tag/${{ steps.get-latest-release.outputs.LATEST_TEMPLATE_RELEASE}}

            To compare the current to latest release, review the releases at:
            https://github.com/ESKYoung/cookiecutter-machine-learning/releases
          branch: cruft/update-to-${{ steps.get-latest-release.outputs.LATEST_TEMPLATE_RELEASE}}
          delete-branch: true
          title: "chore: incorporate new `cruft` updates"
          body: |
            This Pull Request (PR) has been autogenerated.

            `cruft` has detected changes due to a [new release of `ESKYoung/cookiecutter-machine-learning`](https://github.com/ESKYoung/cookiecutter-machine-learning/releases/tag/${{ steps.get-latest-release.outputs.LATEST_TEMPLATE_RELEASE}}).

            Please review these changes carefully, as [there may have been more than one release since the last update](https://github.com/ESKYoung/cookiecutter-machine-learning/releases); the current release is `${{ steps.check-cruft-link.outputs.CURRENT_TEMPLATE_RELEASE}}`, and the latest release is `${{ steps.get-latest-release.outputs.LATEST_TEMPLATE_RELEASE}}`.

            Push any additional commits to this PR to add/amend/remove changes as required.

            If you wish to discard the changes, raise a separate PR with only the changes in `.cruft.json` listed here.
