name: "Run `nox` sessions"

on: [pull_request]

jobs:
  nox:
    name: ${{ matrix.os }} / ${{ matrix.python }} / ${{ matrix.nox_session }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python: ["3.10"]
        nox_session: ["docs", "pre-commit", "testing"]
        exclude:
          - os: macos-latest
            nox_session: "docs"
          - os: macos-latest
            nox_session: "pre-commit"
          - python: "3.10"
            nox_session: "docs"
          - python: "3.10"
            nox_session: "pre-commit"
      fail-fast: true
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout the revision
        uses: actions/checkout@v3

      - name: Install Poetry
        id: install-poetry
        uses: ./.github/actions/install-poetry
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies for `docs` `nox` session
        if: ${{ matrix.nox_session == 'docs' }}
        run: poetry install --with=ci-cd,docs --sync --no-ansi

      - name: Install dependencies for `pre-commit` `nox` session
        if: ${{ matrix.nox_session == 'pre-commit' }}
        run: poetry install --with=ci-cd,pre-commit,notebook,testing --sync --no-ansi

      - name: Install dependencies for `testing` `nox` session
        if: ${{ matrix.nox_session == 'testing' }}
        run: poetry install --with=ci-cd,testing --sync --no-ansi

      - name: Run `nox` session `${{ matrix.nox_session }}`
        run: poetry run nox --force-python python --session ${{ matrix.nox_session }}
