name: "Build, and deploy `Sphinx` documentation"

on:
  release:
    types: [released]

env:
  POETRY_VERSION: 1.7.1
  PYTHON_VERSION: 3.10

jobs:
  sphinx-build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the revision
        uses: actions/checkout@v4

      - name: Install Poetry
        id: install-poetry
        uses: ./.github/actions/install-poetry
        with:
          poetry-version: ${{ env.POETRY_VERSION }}
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Cache Poetry virtual environment
        uses: actions/cache@v4
        id: cache
        with:
          path: .venv
          key: cache-main-poetry-venv-${{ runner.os }}-${{ steps.install-poetry.outputs.full-python-version }}-${{ env.POETRY_VERSION }}-${{ hashFiles('poetry.lock') }}
          restore-keys: cache-main-poetry-venv-${{ runner.os }}-${{ steps.install-poetry.outputs.full-python-version }}-${{ env.POETRY_VERSION }}-

      - name: Install dependencies
        run: poetry install --with=docs --sync --no-ansi
        shell: bash

      - name: Build documentation
        run: poetry run sphinx-build -b html docs/ docs/_build
        shell: bash

      - name: Deploy documentation to GitHub Pages
        if: ${{ startsWith(github.ref, 'refs/tags') && !env.ACT }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs/_build
