name: "Build, and deploy `Sphinx` documentation"

on:
  release:
    types: [released]

env:
  PYTHON_VERSION: "3.10"

jobs:
  sphinx-build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout the revision
        uses: actions/checkout@v4

      - name: Install Poetry
        id: install-poetry
        uses: ./{{ cookiecutter.repository_name }}/.github/actions/install-poetry
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Cache Poetry virtual environment
        uses: actions/cache@v4
        id: cache
        with:
          path: .venv
          key: cache-${{ github.repository }}-main-${{ github.job }}-poetry-venv-${{ runner.os }}-${{ steps.install-poetry.outputs.full-python-version }}-${{ hashFiles('poetry.lock') }}
          restore-keys: cache-${{ github.repository }}-main-${{ github.job }}-poetry-venv-${{ runner.os }}-${{ steps.install-poetry.outputs.full-python-version }}-

      - name: Install dependencies
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        run: poetry install --only=main,docs --sync --no-ansi

      - name: Build documentation
        run: poetry run sphinx-build -b html docs/ docs/_build

      - name: Deploy documentation to GitHub Pages
        if: ${{ startsWith(github.ref, 'refs/tags') && !env.ACT }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs/_build
